services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuln_scanner_app
    environment:
      DATABASE_URL: sqlite:////app/data/vuln_scanner.db
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice_shop_app
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  sqlite_data:
