[project]
name = "vuln-scanner"
version = "1.0.0"
description = "Escáner de vulnerabilidades web básico"
authors = [{ name = "DataFrame_gang", email = "dataframe@email.com" }]
requires-python = ">=3.10"
dependencies = [
    "scrapy",
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "alembic",
    "pydantic",
    "pydantic-settings",
    "jinja2",
    "python-dotenv",
    "psycopg2-binary",
    "beautifulsoup4",
]

[tool.poetry]
packages = [
    { include = "database" },
    { include = "core" },
    { include = "dashboard" },
    { include = "scanner" },
]
